AcerCMS/Models/News.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcerCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string ShortDesctription { get; set; }
        public string Content { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public bool IsDeleted { get; set; }
        public int ViewCount { get; set; }
        public Nullable<int> PictureId { get; set; }
    
        public virtual Picture Picture { get; set; }
    }
}

AcerCMS/Models/NewsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AcerCMS.Models
{
    public class NewsViewModel
    {
        public News News { get; set; }
        public List<Comment> Comments { get; set; }
        public Comment Comment { get; set; }
    }
}

AcerCMS/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AcerCMS.Models;

namespace AcerCMS.Controllers
{
    public class NewsController : Controller
    {
        // GET: News
        public ActionResult Index()
        {
            var model = new List<News>();
            using (var db = new AcerCmsEntities())
            {
                model = db.News.OrderByDescending(o=> o.UpdateDate).ToList();
            }
            return View(model);
        }

        public ActionResult ReadNews(int id)
        {
            using (var db= new AcerCmsEntities())
            {
                var model = db.News.Find(id);

                if (model == null)
                    return HttpNotFound("Haber Bulunamadı!");
                
                return View(model);
            }
        }

    }
}

AcerCMS/Views/News/Index.cshtml
@model IEnumerable<AcerCMS.Models.News>

@{
    ViewBag.Title = "Haberler Ve Duyurular";
}

<h2>Son Haberler</h2>
@if (Model.Any())
{
    <ul class="list-group">

        @foreach (var news in Model)
        {
            <li class="list-group-item">
                <h3>
                    @news.Title <small>@news.UpdateDate.ToShortDateString()</small>
                    <span class="label label-info">@news.ViewCount</span>
                </h3>
                <p class="lead">@news.ShortDesctription</p>
                <p class="text-right">
                    @Html.ActionLink("Devami için Tıklayınız...", "ReadNews", "News", new {id= news.Id}, null)
                </p>
            </li>
        }
    </ul>
}
else
{
    <div class="alert alert-warning">
        Henüz Haber Eklenmemiş!
    </div>
}

AcerCMS/Views/News/ReadNews.cshtml
@model AcerCMS.Models.News

@{
    ViewBag.Title = Model.Title;
}

<h2>@Model.Title </h2>
<p class="lead">@Model.ShortDesctription</p>

<hr />

<div>
    @Model.Content
</div>